### ISSUE TITLE
Endless ACPI errors. Laptop doesn't boot. 

### ISSUE THREAD

**Issue by trebabcock** [dandepeched/Hackintosh-ThinkPad-E580#1]
I followed a guide to get macOS working on my Thinkpad, then added these files after installing Clover on my hard drive. The screen just shows a bunch of ACPI errors, and keeps scrolling for about 20 minutes, then I get an Apple logo, but the progress bar doesn't move.

**Comment by samtheprogram** [comment]
What are the ACPI errors? Can't help unless we know what is causing the issue. Are you on a ThinkPad E580? I have an E480 and it seems from the looks of it that these ACPI files would work on my machine (although I am not using them on my machine).

**Comment by dandepeched** [comment]
@trebabcock I'm sorry but without the details I won't be able to help you.
I've recently upgraded my configuration to Catalina and also mentioned that Secure Boot should be disabled in BIOS. You can try new configuration and provide more details if it won't help.
