### ISSUE TITLE
Can I install this on a SATA SSD on my ThinkPad?

### ISSUE THREAD

**Issue by m-obeid** [dandepeched/Hackintosh-ThinkPad-E580#13]
I want to keep my Windows installation on my NVMe SSD.
Can I just install to a Samsung 860 EVO SATA SSD?

macOS 11 Big Sur

**Comment by dandepeched** [comment]
@m-obeid , not sure what exact configuration you are aiming, but here is example of mine:
SSD partitions: Windows EFI, Windows system, MacOS system
HDD partitions: Open Core EFI, data partitions
