### ISSUE TITLE
How to fix audio?

### ISSUE THREAD

**Issue by luffytalory** [dandepeched/Hackintosh-ThinkPad-E580#2]
when I use this clove, my audio can't run, how can I fix it

**Comment by sh0umik** [comment]
Any fixes yet ?

**Comment by bonexd** [comment]
set alcid=15 as a boot arg, or set your audio inject to 15

**Comment by dandepeched** [comment]
@luffytalory, @sh0umik, were you able to resolve your issue? It is possible that there is some different audio chip installed in your system. Please check which one you have on board.
