### ISSUE TITLE
Infos about the Battery Status & Fn shortcuts issue after waking from sleep

### ISSUE THREAD

**Issue by SukkaW** [dandepeched/Hackintosh-ThinkPad-E580#3]
I am using ThinkPad E480 which has almost identical DSDT. I have noticed that the battery stat won't update after waking from sleep:

- If the laptop is has no AC plugged in before sleep, then it will shows uncharged even when AC is plugged in after waking.
- If the laptop is has AC plugged in before sleep, then it will shows charging even when AC is off after waking.

And, Fn shortcuts isn't functioning as well (with FnLock light on) after waking from sleep.

It seems that those two problem are connected: either Fn & Battery status work at the same time, or the two neither work at the same time.

Hopefully the information could help you debugging with DSDT & SSDT. So far I see no relationship between them.

**Comment by SukkaW** [comment]
I have noticed the function `FNST ()`, which means `FnSticky`. I believe it is related with Fn shortcuts (and it is called inside `OWAK ()` as well).

**Comment by SukkaW** [comment]
I am here to confirm that the issue can be found on those ThinkPad machine:

- E470
- E480
- E490
- R480

**Comment by Rovitz** [comment]
Same issue with my ThinkPad L480, FN keys stop working on wake with FnLock light on
