### ISSUE TITLE
大佬，我也是E580   声卡用不了啊

### ISSUE THREAD

**Issue by Mohoward** [dandepeched/Hackintosh-ThinkPad-E580#5]

**Comment by macjohson** [comment]
你电量显示了？

**Comment by Mohoward** [comment]
> 你电量显示了？

是的，显示了

**Comment by macjohson** [comment]
> > 你电量显示了？
> 
> 是的，显示了

我的不显示啊，bios也降了，声音没问题

**Comment by Mohoward** [comment]
> > > 你电量显示了？
> > 
> > 
> > 是的，显示了
> 
> 我的不显示啊，bios也降了，声音没问题

我是从t480efi顺了个补丁过来，好了   电量显示还挺准确

**Comment by macjohson** [comment]
> > > > 你电量显示了？
> > > 
> > > 
> > > 是的，显示了
> > 
> > 
> > 我的不显示啊，bios也降了，声音没问题
> 
> 我是从t480efi顺了个补丁过来，好了 电量显示还挺准确

大哥，求教，我现在就电量问题

**Comment by Mohoward** [comment]
别，我也只是搬运工而已



---原始邮件---
发件人: "macjohson"<notifications@github.com&gt;
发送时间: 2020年4月12日(周日) 晚上9:18
收件人: "dandepeched/Hackintosh-ThinkPad-E580"<Hackintosh-ThinkPad-E580@noreply.github.com&gt;;
抄送: "JackMo"<312566796@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [dandepeched/Hackintosh-ThinkPad-E580] 大佬，我也是E580   声卡用不了啊 (#5)




     
你电量显示了？
  
是的，显示了
  
我的不显示啊，bios也降了，声音没问题
  
我是从t480efi顺了个补丁过来，好了 电量显示还挺准确
  
大哥，求教，我现在就电量问题

**Comment by Mohoward** [comment]
> > > > > 你电量显示了？
> > > > 
> > > > 
> > > > 是的，显示了
> > > 
> > > 
> > > 我的不显示啊，bios也降了，声音没问题
> > 
> > 
> > 我是从t480efi顺了个补丁过来，好了电量显示还挺准确
> 
> 大哥，求教，我现在就电量问题

你加我qq吧，我给你发过去，你试下

**Comment by macjohson** [comment]
> > > > > > 你电量显示了？
> > > > > 
> > > > > 
> > > > > 是的，显示了
> > > > 
> > > > 
> > > > 我的不显示啊，bios也降了，声音没问题
> > > 
> > > 
> > > 我是从t480efi顺了个补丁过来，好了电量显示还挺准确
> > 
> > 
> > 大哥，求教，我现在就电量问题
> 
> 你加我qq吧，我给你发过去，你试下

你qq多少

**Comment by Mohoward** [comment]
> > > > > > > 你电量显示了？
> > > > > > 
> > > > > > 
> > > > > > 是的，显示了
> > > > > 
> > > > > 
> > > > > 我的不显示啊，bios也降了，声音没问题
> > > > 
> > > > 
> > > > 我是从t480efi顺了个补丁过来，好了电量显示还挺准确
> > > 
> > > 
> > > 大哥，求教，我现在就电量问题
> > 
> > 
> > 你加我qq吧，我给你发过去，你试下
> 
> 你qq多少

312566796。 刚网速太卡了

**Comment by dandepeched** [comment]
@Mohoward, were you able to resolve your issue? It is possible that there is some different audio chip installed in your system. Please check which one you have on board.
