### ISSUE TITLE
Lid close and FN keys stop working 临时解决方法

### ISSUE THREAD

**Issue by Zui-Qing-Feng** [dandepeched/Hackintosh-ThinkPad-E580#7]
最近找到了一个临时解决的方法，就是在 '偏好设置->节能' 里面的电池和电源适配器都设置为3小时或永不(也就是尽量不睡眠)，然后在 '偏好设置-桌面与屏幕保护程序-屏幕保护程序' 选择开始前闲置20分钟，然后选择一个你喜欢的壁纸即可，然后在 '偏好设置-安全性与隐私'勾选上"进入睡眠或开始屏幕保护程序`立即`要求输入密码"便设置完成了。毕竟屏幕保护也不是特别好点，而且输入密码开启时候并不影响Fn等其他F1、F2等键盘的作用，我觉得可以尝试临时先用屏幕保护来解决睡眠的bug，毕竟每次重启电脑都影响工作效率。

**Comment by dandepeched** [comment]
@Zui-Qing-Feng, I didn't fully understand your proposal. Do you mean to always keep laptop powered (never allow sleep)?

**Comment by Zui-Qing-Feng** [comment]
> @Zui-Qing-Feng, I didn't fully understand your proposal. Do you mean to always keep laptop powered (never allow sleep)?

yes,Almost exactly what it means. But this is only a temporary solution.😂

**Comment by xqdxqd** [comment]
> 最近找到了一个临时解决的方法，就是在 '偏好设置->节能' 里面的电池和电源适配器都设置为3小时或永不(也就是尽量不睡眠)，然后在 '偏好设置-桌面与屏幕保护程序-屏幕保护程序' 选择开始前闲置20分钟，然后选择一个你喜欢的壁纸即可，然后在 '偏好设置-安全性与隐私'勾选上"进入睡眠或开始屏幕保护程序`立即`要求输入密码"便设置完成了。毕竟屏幕保护也不是特别好点，而且输入密码开启时候并不影响Fn等其他F1、F2等键盘的作用，我觉得可以尝试临时先用屏幕保护来解决睡眠的bug，毕竟每次重启电脑都影响工作效率。

可以试试禁用s3

**Comment by xqdxqd** [comment]
hi,  i use https://github.com/1Revenger1/ECEnabler instead of battery hotpath.
battery status can update correctly。fn keys still stop working.

**Comment by dandepeched** [comment]
@xqdxqd , how do you use it? show example if possible

**Comment by xqdxqd** [comment]
@dandepeched just disable  your battery hotpatch and add ECEnabler.kext

**Comment by dandepeched** [comment]
@xqdxqd , hotpatch is not used anymore as it stopped working at some point. Now I use patched DSDT file. Removing it leads to battery not being detected and ECEnabler doesn't help with this issue. ECEnabler also didn't help with battery status stuck after sleep. So for me it doesn't do anything :)
