### ISSUE TITLE
Instant reboot at the beginning

### ISSUE THREAD

**Issue by rabbit-93** [dandepeched/Hackintosh-ThinkPad-E580#8]
If I try to boot in clover from mac os recovery, my ThinkPad instantly reboots. No logs in verbose. Do i have to modify the files from repo?

**Comment by sudoxd** [comment]
try adding npci=0x3000 as a boot flag

**Comment by rabbit-93** [comment]
It freezes the boot

**Comment by dandepeched** [comment]
@rabbit-93, were you able to resolve your issue?

**Comment by rabbit-93** [comment]
@dandepeched unfortunately not

**Comment by dandepeched** [comment]
@rabbit-93 , please give some step by step guide on what you see, cause from description I don't fully got what you are trying to do and when exactly you see reboot
